version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: resumeskillgapacr.azurecr.io/resumeskillgap-backend:latest
    container_name: resumeskillgap-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: resumeskillgapacr.azurecr.io/resumeskillgap-frontend:latest
    container_name: resumeskillgap-frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://backend:8000/api
    depends_on:
      - backend
