name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      # 1. Checkout & Python
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 2. Install deps + spaCy model (needed for your parser)
      - name: Install deps & spaCy model
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      # 4. Run test
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
